models:
  lasso:
    alpha: [ 0.01, 0.1, 1, 10, 100]
    fit_intercept: [true]
    max_iter: [10000]
  ridge:
    alpha: [ 0.01, 0.1, 1, 10, 100]
    fit_intercept: [true]
    max_iter: [10000]
  elasticnet:
    alpha: [ 0.01, 0.1, 1, 10, 100]
    l1_ratio: [0.1, 0.5, 0.9]
    fit_intercept: [true]
    max_iter: [10000]
  randomforest:
    n_estimators: [100, 300, 500]
    max_depth: [null, 10, 20]
    min_samples_leaf: [1, 2, 5, 10]
    min_samples_split: [2, 5, 10]
    max_features: ["sqrt", "log2", 0.5, 1.0]
    random_state: [42]
  pcr:
    n_components: [10, 20, 40]
preprocess:
  flag_scale: [true, false]
  num_strat: ["median","mean"]
  cat_strat: ["most_frequent","constant"]