models:
  ridge:
    alpha: [1.0, 10.0, 50.0, 100.0]
    fit_intercept: [true]
  elasticnet:
    alpha: [0.01, 0.1, 1.0, 10.0]
    l1_ratio: [0.1, 0.5, 0.9]
    fit_intercept: [true]
    max_iter: [10000]
preprocess:
  flag_scale: [true, false]
  num_strat: ["median"]
  cat_strat: ["most_frequent"]